<?php
/**
 * Copyright © Mangoit, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<?php $_option = $block->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?= ($_option->getRequired()) ? ' required': '' ?>">
    <label class="label">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>]"
                       value="<?= /* @escapeNotVerified */ $_selections[0]->getSelectionId() ?>"/>
            <?php else:?>
                <?php foreach($_selections as $_selection): ?>
                    <div class="field choice">
                        <input class="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?> checkbox product bundle option change-container-classname"
                               id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>"
                               type="checkbox"
                               <?php if ($_option->getRequired()) /* @escapeNotVerified */ echo 'data-validate="{\'validate-only-one-checkbox-required-by-name\':\'input[name^=&quot;bundle_option[' . $_option->getId() . ']&quot;]:checked\'}"'?>
                               name="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>][<?= /* @escapeNotVerified */ $_selection->getId() ?>]"
                               data-selector="bundle_option[<?= /* @escapeNotVerified */ $_option->getId() ?>][<?= /* @escapeNotVerified */ $_selection->getId() ?>]"
                               <?php if ($block->isSelected($_selection)) echo ' checked="checked"' ?>
                               <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>
                               value="<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>"/>
                        <label class="label"
                               for="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-<?= /* @escapeNotVerified */ $_selection->getSelectionId() ?>">
                            <span><?= /* @escapeNotVerified */ $block->getSelectionQtyTitlePrice($_selection) ?></span>
                        </label>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?= /* @escapeNotVerified */ $_option->getId() ?>-container"></div>
            <?php endif; ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    require([
        "jquery",
        "mage/calendar",
        "jquery/validate",
        "mage/validation"
    ], function(jQuery){
        jQuery.validator.addMethod('validate-only-one-checkbox-required-by-name', function (v, elm, selector) {
                var name = elm.name.replace(/([\\"])/g, '\\$1'),
                    container = this.currentForm;
                var divName= name.split("]")[0]+']';
                divName = divName.replace(/[[\]]/g,'_');
                selector = selector === true ? 'input[name="' + name + '"]:checked' : selector;
                if(!container.querySelectorAll(selector).length) {
                    console.log(jQuery('#'+divName+'-error'));
                    console.log(divName);
                    jQuery('#'+divName+'-error').remove();
                    jQuery('<div for="'+divName+'" generated="true" class="'+divName+'-error mage-error" id="'+divName+'-error" style="display: block;margin-bottom: 7px;">Please select one of the options.</div>').insertAfter(jQuery(elm).closest('.control').find('.nested.options-list'));
                }
                return !!container.querySelectorAll(selector).length;
            },
        '');

    }); 
</script>